on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/ne1to2ia-3ib4et5o@cron
        with:
          token: ${{ secrets.token }}
